### ISSUE TITLE
Save the resulting PNG in the note (instead of the draw object)

### ISSUE THREAD

**Issue by Thulium-Drake** [marc0l92/joplin-plugin-drawio#5]
Hi there!

I was wondering whether it would be possible that the object that's inserted in the note can be the PNG (or SVG) instead of the draw file, as this would also allow for example the mobile app to show schematics made in the plugin (as the mobile app doesn't have plugin support at the moment)

Thank you!

**Comment by marc0l92** [comment]
That would be possible, but then I don't know how to distinguish between normal images and images built with the plugin.

I need to differentiate them because I want to show the right click menu only on the images created with this plugin.

But maybe I can find another way... I'm open to suggestions

**Comment by Thulium-Drake** [comment]
Perhaps you could name the images something like ```drawio_<ID>.png```. Where the ID is the number that's generated by the plugin right now to identify which graph to load, which could then also be an easy way to 'upgrade' existing notes

**Comment by marc0l92** [comment]
I'm modifying the plugin in order to use in the markdown something like this:
```md
![drawio](:/a83e6f7d88f04c56bf9e1150df9fc7b4)
```

what do you think?

**Comment by marc0l92** [comment]
In version 2.0 I'm using the classic image makrdown syntax.

**Comment by Thulium-Drake** [comment]
Works like a charm!
